FROM ubuntu:22.04
MAINTAINER Jaric Zola <jzola@buffalo.edu>

RUN apt-get update --fix-missing
RUN apt-get upgrade

RUN apt-get install -y apt-utils
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y make
RUN apt-get install -y cmake
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y build-essential
RUN apt-get install -y unzip
RUN apt-get install -y gawk
RUN apt-get install -y git

RUN apt install -y python3
RUN apt install -y rustc
RUN apt install -y golang-go
RUN apt install -y default-jre
RUN apt install -y scala

# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN apt-get update && apt-get install -y sudo 
RUN apt-get install -y git
RUN git clone https://github.com/UBAutograding/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# Clean up
WORKDIR /home
RUN apt-get -y autoremove
RUN rm -rf Tango/
